modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
# issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "limlib"
version = "${version}"
displayName = "${mod_name}"
# updateJSONURL = "https://change.me.example.invalid/updates.json"
# displayURL = "https://change.me.to.your.mods.homepage.example.invalid/"
credits = "${credits}"
authors = "${neoforge_mod_authors}"
#enumExtensions = "META-INF/limlib.enumextensions.json"
description = '''${description}'''
logoFile = "assets/limlib/icon.png"

[[mixins]]
config = "limlib.mixins.json"

[[mixins]]
config = "limlib.neoforge.mixins.json"

[[mixins]]
config = "limlib.specialmodels.mixins.json"

[[mixins]]
config = "limlib.specialmodels-neoforge.mixins.json"

[[mixins]]
config = "limlib.specialmodels-iris.mixins.json"

[[mixins]]
config = "limlib.specialmodels-sable.mixins.json"

[[mixins]]
config = "limlib.specialmodels-sable-sodium.mixins.json"

[[mixins]]
config = "limlib.specialmodels-sodium.mixins.json"

[[mixins]]
config = "limlib.specialmodels-sodium-neoforge.mixins.json"

[[dependencies.limlib]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.limlib]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.limlib]]
modId = "sable"
type = "optional"
versionRange = "[${sable_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.limlib]]
modId = "sodium"
type = "optional"
versionRange = "[${sodium_min_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.limlib]]
modId = "iris"
type = "optional"
versionRange = "[${iris_min_version},)"
ordering = "NONE"
side = "CLIENT"
